controller_manager:
  ros__parameters:
    update_rate: 30
    #use_sim_time: false

    diff_cont:
      type: diff_drive_controller/DiffDriveController #diff drive

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster #to get wheel tf correct

diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.310
    wheel_radius: 0.035

    use_stamped_vel: false

    # open_loop: false    

    # wheels_per_side: 1
    #wheel_separation_multiplier: 1.0
    #left_wheel_radius_multiplier: 1.0
    #right_wheel_radius_multiplier: 1.0

    #publish_rate: 30.0
    #odom_frame_id: odom    
    #base_frame_id: base_footprint
    # pose_covariance_diagonal: x
    # twist_covariance_diagonal: x
    #open_loop: false
    #enable_odom_tf: true
    #odom_topic: "/odom"


    #cmd_vel_timeout: 0.5
    # publish_limited_velocity: x
    # velocity_rolling_window_size: x
    
    #linear.x.has_velocity_limits: true
    #linear.x.has_acceleration_limits: true
    #linear.x.has_jerk_limits: false
    #linear.x.max_velocity: 10.0
    #linear.x.min_velocity: -10.0
    #linear.x.max_acceleration: 0.5
    #linear.x.max_jerk: 0.0
    #linear.x.min_jerk: 0.0

    #angular.z.has_velocity_limits: true
    #angular.z.has_acceleration_limits: true
    #angular.z.has_jerk_limits: false
    #angular.z.max_velocity: 3.0
    #angular.z.min_velocity: -3.0
    #angular.z.max_acceleration: 1.0
   # angular.z.min_acceleration: -1.0
    #angular.z.max_jerk: 0.0
    #angular.z.min_jerk: 0.0